### ISSUE TITLE
502 Server Error: Bad Gateway for url: https://api.gestdown.info/subtitles/get/[removed]

### ISSUE THREAD

**Issue by alneven** [Belphemur/AddictedProxy#398]
Hi @Belphemur 
is the API down?
Thanks!

**Comment by Belphemur** [comment]
Hey,
Yeah I'm having issue with pg-bouncer and docker.
Trying to figure what's happening.

**Comment by Belphemur** [comment]
Should be good now. I'll monitor if anything else fails.

**Comment by alneven** [comment]
It is working again, thanks!
